"""One-shot converter: docs/specs/AI_CardPayments_Agent_UseCase.docx -> .md.

Re-run after the spec is updated to refresh the markdown rendering used
for git diff and grep. The .docx remains authoritative for formatting.
"""

from __future__ import annotations

import io
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
HEADING_MAP = {"Title": "# ", "Heading1": "## ", "Heading2": "### ", "Heading3": "#### "}

SPEC_DIR = Path(__file__).resolve().parent.parent / "docs" / "specs"
DOCX = SPEC_DIR / "AI_CardPayments_Agent_UseCase.docx"
OUT = SPEC_DIR / "AI_CardPayments_Agent_UseCase.md"


def text_of(node) -> str:
    return "".join((t.text or "") for t in node.iter(f"{{{W}}}t"))


def main() -> int:
    if not DOCX.exists():
        print(f"Source docx not found: {DOCX}", file=sys.stderr)
        return 1

    with zipfile.ZipFile(DOCX) as z:
        xml = z.read("word/document.xml").decode("utf-8")
    body = ET.fromstring(xml).find(f"{{{W}}}body")

    out: list[str] = [
        "# AI Агент за Информационни Репорти в Областта на Картовите Плащания",
        "",
        "> Markdown rendering of `AI_CardPayments_Agent_UseCase.docx`,",
        "> regenerated by `scripts/convert_usecase_docx.py`. The .docx is",
        "> authoritative for formatting; this file exists for git diff and grep.",
        "",
    ]

    for child in list(body):
        tag = child.tag.split("}")[-1]
        if tag == "p":
            style = ""
            pPr = child.find(f"{{{W}}}pPr")
            if pPr is not None:
                ps = pPr.find(f"{{{W}}}pStyle")
                if ps is not None:
                    style = ps.get(f"{{{W}}}val", "")
            line = text_of(child).strip()
            if not line:
                out.append("")
                continue
            if style in HEADING_MAP:
                out.extend(["", HEADING_MAP[style] + line, ""])
            elif style == "ListParagraph":
                out.append(f"- {line}")
            else:
                out.append(line)
        elif tag == "tbl":
            rows: list[list[str]] = []
            for row in child.iter(f"{{{W}}}tr"):
                cells = []
                for cell in row.iter(f"{{{W}}}tc"):
                    txt = text_of(cell).strip().replace("|", "\\|").replace("\n", " ")
                    cells.append(txt)
                rows.append(cells)
            if not rows:
                continue
            width = max(len(r) for r in rows)
            out.append("")
            header = rows[0] + [""] * (width - len(rows[0]))
            out.append("| " + " | ".join(header) + " |")
            out.append("|" + "|".join(["---"] * width) + "|")
            for r in rows[1:]:
                r = r + [""] * (width - len(r))
                out.append("| " + " | ".join(r) + " |")
            out.append("")

    text = re.sub(r"\n{3,}", "\n\n", "\n".join(out)).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {len(text)} bytes -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    raise SystemExit(main())
