"""Loader for the IRIS transaction-category taxonomy.

The JSON file is generated by ``scripts/convert_transaction_categories.py``
from the source ``Transaction Categories Iris Solutions v.1.1.xlsx``. This
module reads it once, normalizes a handful of whitespace quirks, and exposes
filtered views the MCP resources serve back to the LLM.

Locale: Bulgarian only. Greek entries are filtered upstream at conversion.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

DATA_FILE = Path(__file__).parent / "data" / "transaction_categories.json"


def _normalize(value: Any) -> Any:
    """Replace NBSP with space; recurse into lists/dicts; strip strings."""
    if isinstance(value, str):
        return value.replace("\xa0", " ").strip()
    if isinstance(value, list):
        return [_normalize(item) for item in value]
    if isinstance(value, dict):
        return {key: _normalize(val) for key, val in value.items()}
    return value


@lru_cache(maxsize=1)
def load_categories() -> dict[str, Any]:
    """Read the JSON once and return the full normalized payload."""
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"Transaction categories file not found: {DATA_FILE}. "
            "Run scripts/convert_transaction_categories.py to regenerate it."
        )
    raw = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    return _normalize(raw)


def get_incoming() -> list[dict[str, Any]]:
    """Return only incoming-direction categories (постъпления)."""
    return [
        cat for cat in load_categories()["categories"]
        if cat.get("direction") == "incoming"
    ]


def get_outgoing() -> list[dict[str, Any]]:
    """Return only outgoing-direction categories (плащания / разходи)."""
    return [
        cat for cat in load_categories()["categories"]
        if cat.get("direction") == "outgoing"
    ]


def get_payroll_patterns() -> list[dict[str, Any]]:
    """Return BG payroll description patterns."""
    return load_categories().get("payroll_patterns", [])


def get_counts() -> dict[str, int]:
    """Return the counts block from the payload."""
    return dict(load_categories().get("counts", {}))


__all__ = [
    "load_categories",
    "get_incoming",
    "get_outgoing",
    "get_payroll_patterns",
    "get_counts",
]
